#!/usr/bin/env bash
#is a challenge
check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                numer2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                numer2=$(echo $a*$numer2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                numer2=$3
        fi

        number1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($numer2 > $number1) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$number1
		        number1=$numer2
		        numer2=$numcp
                fi

        echo "$num$number1*$numer2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
